extends RefCounted
class_name GameTuning

# Player movement — values are pixels and seconds at a fixed 60 Hz physics rate.
const PLAYER_MAX_SPEED := 260.0
const PLAYER_GROUND_ACCELERATION := 1600.0
const PLAYER_GROUND_DECELERATION := 2000.0
const PLAYER_GROUND_TURN_ACCELERATION := 2600.0
const PLAYER_AIR_ACCELERATION := 1050.0
const PLAYER_AIR_DECELERATION := 500.0
const PLAYER_AIR_TURN_ACCELERATION := 1450.0
const PLAYER_GRAVITY := 1800.0
const PLAYER_MAX_FALL_SPEED := 900.0
const PLAYER_JUMP_SPEED := 590.0
const PLAYER_JUMP_CUT_SPEED := 210.0
const PLAYER_JUMP_BUFFER := 0.12
const PLAYER_COYOTE_TIME := 0.10
const PLAYER_LANDING_MIN_SPEED := 260.0
const PLAYER_LANDING_FEEDBACK_TIME := 0.16
const PLAYER_LANDING_SQUASH := 0.82
const PLAYER_LANDING_OVERSHOOT := 1.06

# Ground sprint and stamina. Kept independent from normal movement and roll tuning.
const PLAYER_SPRINT_SPEED_MULTIPLIER := 1.80
const PLAYER_SPRINT_SPEED := PLAYER_MAX_SPEED * PLAYER_SPRINT_SPEED_MULTIPLIER
const PLAYER_SPRINT_ACCELERATION := 2100.0
const PLAYER_SPRINT_DECELERATION := 2400.0
const PLAYER_SPRINT_LAND_DECELERATION := 1400.0
const PLAYER_SPRINT_JUMP_SPEED_CAP := PLAYER_SPRINT_SPEED
const PLAYER_SPRINT_JUMP_AIR_ACCELERATION := 360.0
const PLAYER_SPRINT_JUMP_AIR_DRAG := 170.0
const PLAYER_NORMAL_JUMP_AIR_DRAG := PLAYER_AIR_DECELERATION
const PLAYER_SPRINT_JUMP_AIR_REVERSE_ACCELERATION := 720.0
const PLAYER_SPRINT_LAND_VISUAL_TIME := 0.14
const PLAYER_MAX_STAMINA := 100.0
const PLAYER_STAMINA_DRAIN_PER_SECOND := 28.0
const PLAYER_STAMINA_REGEN_PER_SECOND := 22.0
const PLAYER_STAMINA_REGEN_DELAY := 0.60
const PLAYER_STAMINA_RESTART_THRESHOLD := 20.0
const PLAYER_STAMINA_MIN_START := 1.0
const PLAYER_STAMINA_AIR_REGEN_MULTIPLIER := 0.65
const PLAYER_STAMINA_GRENADE_REGEN_MULTIPLIER := 0.65
const PLAYER_STAMINA_HURT_REGEN_PAUSE := 0.28
const PLAYER_SPRINT_WALL_DISTANCE_EPSILON := 0.25
const PLAYER_SPRINT_START_TIME := 0.08
const PLAYER_SPRINT_STOP_TIME := 0.12
const PLAYER_EXHAUSTED_FEEDBACK_TIME := 0.45
const PLAYER_STAMINA_FULL_HIDE_DELAY := 0.50

# Ground roll. The cooldown begins after the movement state finishes.
const PLAYER_DOUBLE_TAP_WINDOW := 0.25
const PLAYER_ROLL_DURATION := 0.30
const PLAYER_ROLL_COOLDOWN := 0.50
const PLAYER_ROLL_SPEED := 340.0

# Player grenade. Charge time is one direction of the ping-pong meter.
const PLAYER_GRENADE_COUNT := 3
const GRENADE_CHARGE_CYCLE := 1.0
const GRENADE_MIN_THROW_SPEED := 340.0
const GRENADE_MAX_THROW_SPEED := 820.0
const GRENADE_HORIZONTAL_VELOCITY_INHERIT := 0.25
const GRENADE_GRAVITY := 1200.0
const GRENADE_FUSE := 1.70
const GRENADE_BOUNCE_DAMPING := 0.56
const GRENADE_MAX_BOUNCES := 5
const GRENADE_RADIUS := 110.0
const GRENADE_DAMAGE := 80
const GRENADE_KNOCKBACK := 360.0
const GRENADE_EDGE_DAMAGE_MULTIPLIER := 0.55
const BOSS_RESUPPLY_GRENADES := 2

# Weapon and damage.
const WEAPON_FIRE_INTERVAL := 0.085
const WEAPON_MAGAZINE_SIZE := 32
const WEAPON_RELOAD_TIME := 0.85
const WEAPON_PROJECTILE_SPEED := 1050.0
const WEAPON_DAMAGE := 24
const WEAPON_ACCENT_EVERY := 4
const WEAPON_ACCENT_DAMAGE := 34
const PLAYER_MAX_HEALTH := 100

# Enemy combat.
const ENEMY_DETECTION_RANGE := 760.0
const RIFLE_SPEED := 90.0
const RIFLE_DAMAGE := 11
const RIFLE_PROJECTILE_SPEED := 680.0
const RIFLE_WINDUP := 0.32
const RIFLE_RECOVERY := 0.88
const RUNNER_SPEED := 155.0
const RUNNER_DAMAGE := 16
const HEAVY_SPEED := 58.0
const HEAVY_DAMAGE := 18
const HEAVY_PROJECTILE_SPEED := 560.0
const HEAVY_WINDUP := 0.48
const HEAVY_RECOVERY := 1.18
const ENEMY_ATTACK_READABLE_RANGE := 520.0
const ENCOUNTER_BUFFER_TIME := 0.55
const BOSS_RESUPPLY_HEALTH := 45
const BOSS_RESUPPLY_AMMO_FLOOR := 0.60

# Camera and feedback.
const CAMERA_VELOCITY_LOOK_FACTOR := 0.32
const CAMERA_MOVEMENT_LOOK_LIMIT := 85.0
const CAMERA_AIM_LOOK_PIXELS := 55.0
const CAMERA_MAX_LOOK_AHEAD := 125.0
const CAMERA_SPRINT_LOOK_AHEAD := 38.0
const CAMERA_LOOK_RESPONSE := 7.0
const CAMERA_FOLLOW_RESPONSE := 5.8
const CAMERA_SHAKE_DECAY := 2.4
const CAMERA_SHAKE_PIXELS := 7.0
const CAMERA_RECOIL_DECAY := 15.0
const PLAYER_SHOT_RECOIL_PIXELS := 1.65
const PLAYER_HIT_KNOCKBACK := 185.0
const ENEMY_HIT_KNOCKBACK := 105.0
const NORMAL_HIT_STRENGTH := 0.62
const ACCENT_HIT_STRENGTH := 0.94
const TERRAIN_HIT_STRENGTH := 0.22
const DEATH_RESTART_DELAY := 1.35
const LANDING_CAMERA_TRAUMA := 0.045
