extends RefCounted
class_name GameTuning

# Player movement — values are pixels and seconds at a fixed 60 Hz physics rate.
const PLAYER_MAX_SPEED := 260.0
const PLAYER_GROUND_ACCELERATION := 1600.0
const PLAYER_GROUND_DECELERATION := 2000.0
const PLAYER_GROUND_TURN_ACCELERATION := 2600.0
const PLAYER_AIR_ACCELERATION := 1050.0
const PLAYER_AIR_DECELERATION := 500.0
const PLAYER_AIR_TURN_ACCELERATION := 1450.0
const PLAYER_GRAVITY := 1800.0
const PLAYER_MAX_FALL_SPEED := 900.0
const PLAYER_JUMP_SPEED := 590.0
const PLAYER_JUMP_CUT_SPEED := 210.0
const PLAYER_JUMP_BUFFER := 0.12
const PLAYER_COYOTE_TIME := 0.10
const PLAYER_LANDING_MIN_SPEED := 260.0
const PLAYER_LANDING_FEEDBACK_TIME := 0.16
const PLAYER_LANDING_SQUASH := 0.82
const PLAYER_LANDING_OVERSHOOT := 1.06

# Weapon and damage.
const WEAPON_FIRE_INTERVAL := 0.085
const WEAPON_MAGAZINE_SIZE := 32
const WEAPON_RELOAD_TIME := 0.85
const WEAPON_PROJECTILE_SPEED := 1050.0
const WEAPON_DAMAGE := 24
const WEAPON_ACCENT_EVERY := 4
const WEAPON_ACCENT_DAMAGE := 34
const PLAYER_MAX_HEALTH := 100

# Enemy combat.
const ENEMY_DETECTION_RANGE := 760.0
const RIFLE_SPEED := 90.0
const RIFLE_DAMAGE := 11
const RIFLE_PROJECTILE_SPEED := 680.0
const RIFLE_WINDUP := 0.32
const RIFLE_RECOVERY := 0.88
const RUNNER_SPEED := 155.0
const RUNNER_DAMAGE := 16
const HEAVY_SPEED := 58.0
const HEAVY_DAMAGE := 18
const HEAVY_PROJECTILE_SPEED := 560.0
const HEAVY_WINDUP := 0.48
const HEAVY_RECOVERY := 1.18
const ENEMY_ATTACK_READABLE_RANGE := 520.0
const ENCOUNTER_BUFFER_TIME := 0.55
const BOSS_RESUPPLY_HEALTH := 45
const BOSS_RESUPPLY_AMMO_FLOOR := 0.60

# Camera and feedback.
const CAMERA_VELOCITY_LOOK_FACTOR := 0.32
const CAMERA_MOVEMENT_LOOK_LIMIT := 85.0
const CAMERA_AIM_LOOK_PIXELS := 55.0
const CAMERA_MAX_LOOK_AHEAD := 125.0
const CAMERA_LOOK_RESPONSE := 7.0
const CAMERA_FOLLOW_RESPONSE := 5.8
const CAMERA_SHAKE_DECAY := 2.4
const CAMERA_SHAKE_PIXELS := 7.0
const CAMERA_RECOIL_DECAY := 15.0
const PLAYER_SHOT_RECOIL_PIXELS := 1.65
const PLAYER_HIT_KNOCKBACK := 185.0
const ENEMY_HIT_KNOCKBACK := 105.0
const NORMAL_HIT_STRENGTH := 0.62
const ACCENT_HIT_STRENGTH := 0.94
const TERRAIN_HIT_STRENGTH := 0.22
const DEATH_RESTART_DELAY := 1.35
const LANDING_CAMERA_TRAUMA := 0.045
